"""Alter User table

Revision ID: ce88341705d8
Revises: f48a5adcf697
Create Date: 2020-07-13 22:48:13.139602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce88341705d8'
down_revision = 'f48a5adcf697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
