"""Alter CostRequest table

Revision ID: f48a5adcf697
Revises: 2e81df19af6b
Create Date: 2020-07-12 16:45:37.575626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f48a5adcf697'
down_revision = '2e81df19af6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('costrequest', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('costrequest', sa.Column('succeed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('costrequest', 'succeed')
    op.drop_column('costrequest', 'created_at')
    # ### end Alembic commands ###
